Update MFEM tutorial description and add TOMMS tutorial
LACES-LAB/documentation pull request #13
Opened 2024-01-27 19:52 UTC by Fuad-HH

I have added a few lines on TOMMS so that if someone new is asked to install TOMMS, they may find this helpful that he needs to get access first.

I've also added the instruction to build MFEM with cmake since MFEM website only gives instructions for make and users may have dig slightly deeper to get the cmake instructions. It may work as a quick reference for us.

2024-01-27 19:55 UTC, Fuad-HH commented
Could you please give me some suggestions on what kind of tutorials for TOMMS and MFEM we can add? Because MFEM tutorials on their website are very comprehensive. And for TOMMS, I don't understand it fully to think of a tutorial. Instruction to run samples are already given in the TOMMS repo wiki.

2024-01-29 03:14 UTC, jacobmerson commented
"tutorial" might not be the right section, but we should have any information about installation, etc. that is specific to us. For TOMMS, the installation instructions will be relevant to SCOREC machines, so just point at that documentation, so a new user to our lab can find it.

Everything is in the perspective of a new person joining the "LACES" team. So, if we can point them to the appropriate link it'll make the startup process just a bit easier. What you say is correct otherwise. We do not want to reinvent the wheel here.

2024-01-29 03:16 UTC, jacobmerson requested changes

2024-01-29 03:16 UTC, jacobmerson commented on content/tutorials/tomms/_index.md
> +Complete installation instructions and usage are available in the TOMMS repository wiki. No special measures are required except changing the configuration files to point to the appropriate directori
Add the link to TOMMS here.

2024-01-29 03:16 UTC, jacobmerson commented on content/tutorials/mfem/_index.md
> +>[MFEM](mfem.org) is a free, lightweight, scalable C++ library for finite element methods.
This is great, specific information for how to install on our systems! Thanks!

2024-01-29 06:07 UTC, Fuad-HH commented on content/tutorials/tomms/_index.md
> +Complete installation instructions and usage are available in the TOMMS repository wiki. No special measures are required except changing the configuration files to point to the appropriate directori
Added.

2024-01-29 06:09 UTC, Fuad-HH commented
> "tutorial" might not be the right section, but we should have any information about installation, etc. that is specific to us. For TOMMS, the installation instructions will be relevant to SCOREC machines, so just point at that documentation, so a new user to our lab can find it.
> 
> Everything is in the perspective of a new person joining the "LACES" team. So, if we can point them to the appropriate link it'll make the startup process just a bit easier. What you say is correct otherwise. We do not want to reinvent the wheel here.

Yes, I was also thinking that all the installation process has gone to the tutorial section. But if we want to relocate them to a different place, that will be a lot of work. If you have any suggestions on doing this easily, please let me know. We can also change the name of the section as "Installation and Tutorials" if it really makes sense.

2024-02-11 23:02 UTC, Fuad-HH commented
Do I need to add anything else?

2024-02-12 20:57 UTC, jacobmerson approved these changes

2024-02-12 20:57 UTC, merged